name: fd_admin
description: "Food and Drugs Administration"
publish_to: "none"
version: 0.1.9

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  #State Management -----------------------------
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get: ^4.7.2
  #----------------------------------------------

  #Utility packages etc. -------------------------------
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  logger: ^2.5.0
  webview_flutter: ^4.13.0
  dio: ^5.8.0+1
  #----------------------------------------------

  #Animation, Icons etc. -------------------------------
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0
  #----------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/fdaLogo.png"

flutter:
  uses-material-design: true

  #Lokalde bulunan assetler ---------------------------------------
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/logos/
    - assets/images/animals/
    - assets/lottie/

  #Lokalde bulunan fontlar ----------------------------------------
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Variable.ttf
        - asset: fonts/Satoshi-VariableItalic.ttf
