import 'package:fd_admin/app/common/constants/image_paths.dart';
import 'package:fd_admin/app/common/constants/string_constants.dart';

enum SectionedCardEnums {
  aboutSection1(
    Stringler.aboutSection1Title,
    Stringler.aboutSection1Info,
    ImagePaths.about1,
  ),
  aboutSection2(
    Stringler.aboutSection2Title,
    Stringler.aboutSection2Info,
    ImagePaths.about2,
  ),
  aboutSection3(
    Stringler.aboutSection3Title,
    Stringler.aboutSection3Info,
    ImagePaths.about3,
  ),
  emergencySection1(
    Stringler.emergencySection1Title,
    Stringler.emergencySection1Info,
    ImagePaths.emergency1,
  ),
  emergencySection2(
    Stringler.emergencySection2Title,
    Stringler.emergencySection2Info,
    ImagePaths.emergency2,
  ),
  emergencySection3(
    Stringler.emergencySection3Title,
    Stringler.emergencySection3Info,
    ImagePaths.emergency3,
  ),
  drugSection1(
    Stringler.drugSection1Title,
    Stringler.drugSection1Info,
    ImagePaths.drug1,
  ),
  drugSection2(
    Stringler.drugSection2Title,
    Stringler.drugSection2Info,
    ImagePaths.drug2,
  ),
  drugSection3(
    Stringler.drugSection3Title,
    Stringler.drugSection3Info,
    ImagePaths.drug3,
  ),
  deviceSection1(
    Stringler.deviceSection1Title,
    Stringler.deviceSection1Info,
    ImagePaths.device1,
  ),
  deviceSection2(
    Stringler.deviceSection2Title,
    Stringler.deviceSection2Info,
    ImagePaths.device2,
  ),
  deviceSection3(
    Stringler.deviceSection3Title,
    Stringler.deviceSection3Info,
    ImagePaths.device3,
  ),
  foodSection1(
    Stringler.foodSection1Title,
    Stringler.foodSection1Info,
    ImagePaths.food1,
  ),
  foodSection2(
    Stringler.foodSection2Title,
    Stringler.foodSection2Info,
    ImagePaths.food2,
  ),
  foodSection3(
    Stringler.foodSection3Title,
    Stringler.foodSection3Info,
    ImagePaths.food3,
  ),
  tobaccoSection1(
    Stringler.tobaccoSection1Title,
    Stringler.tobaccoSection1Info,
    ImagePaths.tobacco1,
  ),
  tobaccoSection2(
    Stringler.tobaccoSection2Title,
    Stringler.tobaccoSection2Info,
    ImagePaths.tobacco2,
  ),
  tobaccoSection3(
    Stringler.tobaccoSection3Title,
    Stringler.tobaccoSection3Info,
    ImagePaths.tobacco3,
  ),
  otherSection1(
    Stringler.otherSection1Title,
    Stringler.otherSection1Info,
    ImagePaths.other1,
  ),
  otherSection2(
    Stringler.otherSection2Title,
    Stringler.otherSection2Info,
    ImagePaths.other2,
  ),
  otherSection3(
    Stringler.otherSection3Title,
    Stringler.otherSection3Info,
    ImagePaths.other3,
  );

  final String title, info, image;

  const SectionedCardEnums(this.title, this.info, this.image);
}
